### ISSUE TITLE
Backend: Develop API function to implement registration.

### ISSUE THREAD

**Issue by abhijeet007rocks8** [Ash515/ExamResultGenerator#18]
Generate a function to take id , password and type as parameter (JSON data) and store it in the database and return appropriate messages in case of successful registration as well as error cases.

**Comment by dilroseR** [comment]
can i do with this on cmd?

**Comment by abhijeet007rocks8** [comment]
I couldn't get you what will you do on cmd ?

**Comment by dilroseR** [comment]
ill make another file which will take id n password from student_login.html using json ,then will create a function in app.py which will take all these parameters and store into the database. is this what you want?

**Comment by abhijeet007rocks8** [comment]
Yes

**Comment by dilroseR** [comment]
ill try doing this
can you assign me this
