### ISSUE TITLE
Backend: Generate API function for implement Login

### ISSUE THREAD

**Issue by abhijeet007rocks8** [Ash515/ExamResultGenerator#20]
Generate a function to accept id and password in json format.
And cross-reference them in the existing login Database.
If the id and password match then return the type of user (student or faculty) the id belongs to.
else return message "Incorrect Id or password"

Note-: If faced any other error handle it and return respective error message.

**Comment by prateekmohanty63** [comment]
Hello I can take this up. Please can you assign me this under SWOC

**Comment by prateekmohanty63** [comment]
There is something not proper in the student login model.
What is the username that I should compare the user input with ?
Because there is only id,password, student and faculty in the login model
so that should i comprare the username with?

**Comment by Ash515** [comment]
Compare with userId

**Comment by Ash515** [comment]
Ok

**Comment by prateekmohanty63** [comment]
I have created the function for login and opened a pull request 
Please merge it
Thank you
