### ISSUE TITLE
Backend: Generate API function to add result of Student by Faculty

### ISSUE THREAD

**Issue by abhijeet007rocks8** [Ash515/ExamResultGenerator#23]
Generate function to-:
Accept-: facultyid, type="faculty", studentid, physics marks, chem marks, maths marks, english marks. in JSON format
and add the studentId and marks of subjects in marks database table.

Return-:
"successfully added" message if sucessfully added to DB
respective error message in case of error
"access denied" if type !="faculty"

**Comment by ashutoshkrris** [comment]
I'd love to work on this issue under Script Winter of Code

**Comment by Ash515** [comment]
Sure

**Comment by sohilkhanduja** [comment]
Can you assign it to me ?? I'd love to work on this issue under Script Winter of Code

**Comment by sohilkhanduja** [comment]
I have created pull request kindly check @ashutoshkrris @Ash515

**Comment by Ash515** [comment]
Merged, Happy Contributing !
