### ISSUE TITLE
Add Contributor.md

### ISSUE THREAD

**Issue by payaldutta** [Ash515/ExamResultGenerator#5]
**Description**
Create Contributors Guideline to help new Contributors get started with this Project.

**Additional Details**
*Add a CONTRIBUTING.md to allow new users to get started with knowing how to contribute.
*Add Screenshots wherever possible.
*Add the basic information about creating Issues, Pull Requests and Branching.
*Mention tutorials related to Git and Github to help them better understand.

**Comment by payaldutta** [comment]
@Ash515 Do assign me this issue under DCP'21.
Thank You.

**Comment by Ash515** [comment]
sorry this is done by other person
