### ISSUE TITLE
Backend: Setup a SQLite Database 

### ISSUE THREAD

**Issue by abhijeet007rocks8** [Ash515/ExamResultGenerator#8]
Database is one of the most important components of the Project. 
So we need to setup and connect the Database to the Flask Backend.

**Comment by harshithatnbr** [comment]
I would like to work on this issue. please assign it to me.

**Comment by Ash515** [comment]
Sure !

**Comment by abhijeet007rocks8** [comment]
@harshithatnbr Any updates on the issue??

**Comment by harshithatnbr** [comment]
I will update by tomorrow sir

**Comment by abhijeet007rocks8** [comment]
@harshithatnbr Any help required??

**Comment by harshithatnbr** [comment]
Sir actually I am not understanding what to do exactly. Can you explain me what to so exactly about the issue .
Thankyou.

**Comment by abhijeet007rocks8** [comment]
> Sir actually I am not understanding what to do exactly. Can you explain me what to so exactly about the issue .
> Thankyou.

Its quite simple actually you need to setup a sqlite db in the app.py flask template in backend folder. 
SQL Alchemy is the package you need to import and setup.

Refer-: https://pythonbasics.org/flask-sqlalchemy/

**Comment by harshithatnbr** [comment]
Thanks a lot for helping me. I will try to solve issue as soon as possible.

**Comment by abhijeet007rocks8** [comment]
@harshithatnbr Any Updates.
if you are finding it difficult then I can have to assign it to someone else.

**Comment by harshithatnbr** [comment]
@abhijeet007rocks8  I will submit by tomorrow morning .I am currently working on this same issue.

**Comment by harshithatnbr** [comment]
I am finding hard to do this . Please assign this issue to someone else . Sorry.
