### ISSUE TITLE
Backend: Create tables in the database required the for Project

### ISSUE THREAD

**Issue by abhijeet007rocks8** [Ash515/ExamResultGenerator#9]
Database is collection of multiple tables.
We would need minimum need two tables at least -:
1. For login Purpose
2. For storing/updating the scores via admin and student.

Note-: Can be more and you will need to identify the parameters needed in tables.
Feel free to contact if you face any issue

**Comment by dilroseR** [comment]
can i try this?

**Comment by abhijeet007rocks8** [comment]
Sure go ahead 
Just share the table schema first as per architecture or face any doubt in that feel free to reach out

**Comment by dilroseR** [comment]
for login table, we can have fields such as username(maybe roll no of the student to login) and password
and for storing/updating scores we can have a table for admin which will have fields such as roll no primary key and subject marks 
is this ok?

**Comment by abhijeet007rocks8** [comment]
> for login table, we can have fields such as username(maybe roll no of the student to login) and password
> and for storing/updating scores we can have a table for admin which will have fields such as roll no primary key and subject marks
> is this ok?

Awesome you can get on with it

**Comment by dilroseR** [comment]
but issue 8 is not yet done

**Comment by dilroseR** [comment]
i can only proceed if the database is set up,right?

**Comment by dilroseR** [comment]
and which all subject's marks should be included??

**Comment by dilroseR** [comment]
if you allow me, i can complete issue 8 as well then proceed with this one

**Comment by abhijeet007rocks8** [comment]
You ca start with table classes setup if the person does not provides update ill assign it to you

**Comment by dilroseR** [comment]
> and which all subject's marks should be included??

??

**Comment by abhijeet007rocks8** [comment]
> > and which all subject's marks should be included??
> 
> ??

Go for 4 subjects for now physics chemistry maths English for now
